services:
  db:
    image: mongo:4
    env_file: 
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-seed:
    image: mongo:4
    depends_on:
      - db
    volumes:
      - ./scripts/movies.json:/app/movies.json
    command: >
      mongoimport -u ${MONGO_USER} -p ${MONGO_PASSWORD} --authenticationDatabase admin --host db --db api --collection movies --type json --file /app/movies.json --jsonArray

  kafka:
    image: mcjesus/kafka:1.0
    environment:
      - KAFKA_ADVERTISED_LISTENER=kafka
    ports:
      - "9092:9092"

  gateway:
    build: ./Gateway
    env_file:
      - .env
    environment:
      - PORT=8081
      - API_URL=${API_URL}
    ports:
      - "8081:8081"
    depends_on:
      - db

  api:
    build: ./Api
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - ALLOWED_IPS=${ALLOWED_IPS}
      - KAFKA_SERVER=${KAFKA_SERVER}:9092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    # ports:
    #   - "8080:8080"
    depends_on:
      - db
      - kafka

  client:
    build: ./Client
    env_file:
      - .env
    environment:
      - PORT=3000
      - API_SERVER=gateway:8081
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mongo-data:
