services:
  db:
    image: mongo
    env_file: 
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-seed:
    image: mongo
    depends_on:
      - db
    volumes:
      - ./scripts/movies.json:/app/movies.json
    command: >
      mongoimport -u ${MONGO_USER} -p ${MONGO_PASSWORD} --authenticationDatabase admin --host db --db api --collection movies --type json --file /app/movies.json --jsonArray

  gateway:
    build: ./Gateway
    env_file:
      - .env
    environment:
      - PORT=${GO_PORT}
      - API_URL=${API_URL}
    ports:
      - "8081:8081"
    depends_on:
      - db

  api:
    build: ./Api
    env_file:
      - .env
    environment:
      - PORT=${CS_PORT}
      - MONGO_URI=${MONGO_URI}
      - KAFKA_SERVER=${KAFKA_SERVER}:9092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build: ./Client
    env_file:
      - .env
    environment:
      - PORT=${NODE_PORT}
      - API_SERVER=api:${CS_PORT}
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    depends_on:
      - db

volumes:
  mongo-data:
